config/routes.rb
Rails.application.routes.draw do
  get '/admins', to: 'admin#index'

  get 'home/index'

	devise_for :users, controllers: {
        registrations: 'registrations'
      }
	root :to => redirect("/users/sign_up")
  
  resources :organisations
	
  #devise_scope :users do
	#  root "users/sign_in", to: "devise/sessions#new"
	#end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :organisation#, required: false

	#validations
	validates :first_address, presence: true
	
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

    def admin?
	  self.is_admin
	end

	#def self.search(params)
	#	org = Organisation.where("org_name like ? or country like ?", "%#{params[:search]}", "%#{params[:search]}") if params[:search].present?
	#	org = org.user.where("email like ?", "%#{params[:search]}")
	#	org
	#end

	
end

app/models/organisation.rb
class Organisation < ApplicationRecord
	belongs_to :user, required: false

	has_one :profile
	has_one :address

	accepts_nested_attributes_for :profile
	accepts_nested_attributes_for :address

	#callbacks

	#before_create :add_user

	#def add_user
	#	self.user_id = current_user
	#end

	#validations

	validates :org_name, presence: true, uniqueness: true
	validates :city, :state, :country, presence: true
	validates :zip_code, numericality: true, length: { is: 6 }
end

app/models/profile.rb
class Profile < ApplicationRecord
	belongs_to :organisation#, required: false


	#validations
	validates :first_name, :last_name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :organisation
  

  #after_create :create_org
  #def create_org
  #	redirect_to new_after_register_path
  #end

  #validations
  validates :email, presence: true, uniqueness: true
  validates :password, length: { in: 6..20 }
  validates_confirmation_of :password, if: :password_required?
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  def index
  	#if  !params[:q]
  	#	@organization = Organisation.all.joins(:profile, :address)
  	#else
  		
  		@search = Organisation.joins(:profile, :address).search(params[:q])#.joins(:profile, :address)
  		@organizations = @search.result.paginate(:page => params[:page], :per_page => 10)
  	#end
  end

  private

  	def check_admin
  		unless current_user.admin?
  			redirect_to home_index_path
  			
  		end
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception


  	def after_sign_in_path_for(resource)
  		if current_user.organisation
  			flash[:notice] = 'You Already created your Organization.' 
	  		home_index_path
	  	else
	  		 new_organisation_path
	  	end
	end

  	#before_action :users_check
  	#def users_check
		#@user = current_user
	#	if user_signed_in?
	#		if current_user == Organisation.find_by(params[:user_id])
	#			redirect_to admin_index_path and return true
	#		else
	#			render home_index_path and return true
	#		end
	#	end
	#end

  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_user_orga
	#include Wicked::Wizard

    #steps :organization

    def new
    	
    	@organisation = Organisation.new
		@organisation.build_profile
    	@organisation.build_address    	

    end

    def create
    	@organisation = Organisation.new(organisation_params)
    	@organisation.user = current_user
    	

    	if @organisation.save
    		 redirect_to home_index_path
    	else
    		render :new
    	end

    	
    end

    private
		def organisation_params
		    params.require(:organisation).permit(:org_name, :org_identifier,:user_id, :zip_code, :city, :state, :country, profile_attributes: [:first_name, :last_name], address_attributes: [:first_address, :second_address])
		end

		def check_user_orga
			unless !current_user.organisation
				redirect_to home_index_path
			end
		end



end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
     super
  end

  # POST /resource
  def create
     super
     #redirect_to(new_after_register_path)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    new_organisation_path
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/after_register_helper.rb
module AfterRegisterHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organization_helper.rb
module OrganizationHelper
end

app/views/admin/index.html.erb
<section class="added-books">
	<div class="">
		<div class="">
			<div class="alert alert-info" role="alert">
			 	<i class="fa fa-heart-o"></i> &emsp;List of Organizations
			</div>
			<div class="books">
				<div class="headers-table">
					<div class="search_form">
						<%= search_form_for @search, url: admins_path do |f| %>

							<div class="">

								<div class="col-md-4 form-group">
									<%= f.text_field :org_name_cont, placeholder: "Company name", class: "form-control" %>
								</div>

								<div class="col-md-3 form-group">
									<%= f.search_field :user_email_cont, placeholder: "Email", class: "form-control" %>
								</div>
								
								<div class="col-md-4 form-group">
									<%= f.text_field :country_cont, placeholder: "country", class: "form-control" %>
								</div>
								
								
							</div>
							<div class="actions">
								<%= f.submit "search", class: "btn btn-primary" %>
							</div>
							
						<% end %>
					</div>
				</div>

				<div class="books-data">
					<table class="table table-bordered">
					    <thead>
					      <tr>
					        <th>id</th>
					        <th>Org name</th>
					        <th>Org Identifier</th>
					        <th>Created by</th>
					        <th>Country</th>
					        <th>Created at</th>
					        <th>Updated at</th>
					      </tr>
					    </thead>
					    <tbody>
					        <% @organizations.each do |o| %>
								<tr>
									<td><%= o.id %></td>
							        <td><%= o.org_name %></td>
							        <td><%= o.org_identifier %></td>
							        <td><%= o.user.email %></td>
							        <td><%= o.country %></td>
							        <td><%= o.created_at.strftime('%v') %></td>
							        <td><%= o.updated_at.strftime('%v') %></td>
							    </tr>
						    <% end %>
					      
					      
					    </tbody>
					</table>
				</div>

				
			</div>

			<div class="digg_pagination text-center">
			    <div class="page_info">
			      <%= page_entries_info @organizations %>
			    </div>
			    <%= will_paginate @organizations, :container => false %>
			</div>

		</div>
	</div>
</section>

app/views/home/index.html.erb
<div class="home_page">
	<div class="row">
		<h3>
			Thank you for registering.<br>
			Well let you know once our product is ready.
		</h3>
	</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if !user_signed_in? %>
        <a class="navbar-brand" href="/">Organization</a>
      <% else %>
        <%=  link_to "Organization", home_index_path, class: "navbar-brand" %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       
       
        
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#"><i class="fa fa-lg fa-dot-circle-o"></i></a></li>
        <% if !user_signed_in? %>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
        <% else %>
            <li><%= link_to "Admin", admins_path if current_user.admin? %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organization</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

  </head>

  <body>
  	<%= render partial: 'layouts/nav' %>
    <div class="container">
    
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>


      <%= yield %>
    </div>
  </body>
</html>

app/views/organisations/_address.html.erb
	<%= f.fields_for :address do |a| %>
		<div class="field form-group">
			<%= a.text_field :first_address, class: "form-control", placeholder: "Line 1" %>
		</div>
		<div class="field form-group">
			<%= a.text_field :second_address, class: "form-control", placeholder: "Line 2" %>
		</div>
	<% end %>

app/views/organisations/_profile.html.erb
	<%= f.fields_for :profile do |p| %>
		<div class="field form-group">
			<%= p.text_field :first_name, class: "form-control", placeholder: "First name" %>
		</div>
		<div class="field form-group">
			<%= p.text_field :last_name, class: "form-control", placeholder: "Last name" %>
		</div>
	<% end %>

app/views/organisations/new.html.erb
<div class="org_form">
	

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@organisation, url: '/organisations', method: :post, validate: true) do |f| %>

			<div class="row">
				<div class="col-md-6">
					<div class="field form-group">
						<%= f.text_field :org_name, id: "name",  class: "form-control", placeholder: "Org name" %>
					</div>
					<div class="field form-group">
						<%= f.text_field :org_identifier, id: "display", class: "form-control", placeholder: "org_identifies", :readonly => true %>
					</div>
				</div>
				<div class="col-md-6">
					<%= render partial: "profile", locals: {f: f} %>
				</div>
			</div>

			<%= render partial: "address", locals: {f: f} %>
			

			<div class="row">
				<div class="col-md-6">
					<div class="field form-group">
						<%= f.text_field :city, class: "form-control", placeholder: "City" %>
					</div>
					<div class="field form-group">
						<%= f.text_field :state, class: "form-control", placeholder: "State" %>
					</div>
				</div>
				<div class="col-md-6">
					<div class="field form-group">
						<%= f.text_field :country, class: "form-control", placeholder: "Country" %>
					</div>
					<div class="field form-group">
						<%= f.text_field :zip_code, class: "form-control" , placeholder: "Zip code" %>
					</div>
				</div>
			</div>
			


			<div class="action text-center">
				<%= f.submit "create", class: "btn btn-block btn-primary" %>
			</div>

		<% end %>
	</div>
</div>
"
<script>
	$('#name').keyup(function() {
	    $('#display').val($(this).val().toLowerCase().split(' ').join('_').replace(/[^a-zA-Z0-9_]/g, ''));
	});
</script>